In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

### Read the set of labels into a dataframe:

In [30]:
labels = pd.read_csv('labels.csv')

In [31]:
labels.head()

perfect_labeler radiologist  algorithm
0          cancer      cancer       0.99
1          cancer      cancer       0.94
2          cancer      cancer       0.73
3          cancer      cancer       0.82
4          cancer      cancer       0.98

### Start with assessing the radiologist's performance:
* Assess the _accuracy_ of the radiologist by just looking at the percent of cases that they correctly labeled
* Next, look at the true positive and true negative rates of the radiologist by generating a _confusion matrix_ 

In [4]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)

In [5]:
radiologist_accuracy

0.8993288590604027

In [6]:
confusion_matrix(labels.perfect_labeler.values,labels.radiologist.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 11, 109]])

### Now look at the algorithm's performance compared to the perfect labeler:
* Since the algorithm doesn't create a binary label, it instead returns a _probability_ of cancer, choose a probability cut-off to use for the algorithm's labeling of cancer vs. bening. _(Hint: 0.5 is a reasonable starting place)_
* Start with assessing _accuracy_ again here
* Generate a confusion matrix

In [25]:
algorithm_prediction = []
for i,r in labels.iterrows():
    if r['algorithm'] > 0.5:
        algorithm_prediction.append('cancer')
    else:
         algorithm_prediction.append('benign')
            

labels['algorithm_prediction'] = algorithm_prediction

algorithm_accuracy = sum(labels.perfect_labeler == labels.algorithm_prediction)/len(labels)
algorithm_accuracy

0.8926174496644296

In [26]:
confusion_matrix(labels.perfect_labeler.values,labels.algorithm_prediction.values,labels=["cancer","benign"])

array([[ 21,   8],
       [  8, 112]])

What happens now if you change the threshold cut-off for your algorithm's classification to 0.4? What if you raise it to 0.6? How do accuracy, fp, fn, tp, and tn change?

In [9]:
algorithm_prediction = []
for i,r in labels.iterrows():
    if r['algorithm'] > 0.4:
        algorithm_prediction.append('cancer')
    else:
         algorithm_prediction.append('benign')
            

labels['algorithm_prediction'] = algorithm_prediction

algorithm_accuracy = sum(labels.perfect_labeler == labels.algorithm_prediction)/len(labels)
algorithm_accuracy

0.8657718120805369

In [10]:
confusion_matrix(labels.perfect_labeler.values,labels.algorithm_prediction.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 16, 104]])

In [11]:
algorithm_prediction = []
for i,r in labels.iterrows():
    if r['algorithm'] > 0.6:
        algorithm_prediction.append('cancer')
    else:
         algorithm_prediction.append('benign')
            

labels['algorithm_prediction'] = algorithm_prediction

algorithm_accuracy = sum(labels.perfect_labeler == labels.algorithm_prediction)/len(labels)
algorithm_accuracy

0.9060402684563759

In [12]:
confusion_matrix(labels.perfect_labeler.values,labels.algorithm_prediction.values,labels=["cancer","benign"])

array([[ 20,   9],
       [  5, 115]])

### Finally, let's compare our algorithm to the radiologist
* A "perfect labeler" might not exist in the real world, and in fact, if often does not
* In AI for medical imaging, using a radiologist's labels as our "true" label is often the standard of practice, and algorithm performance is judged in both an academic setting as well as in the regulated industry landscape based on performance against an expert human

* Repeat the steps above using a set threshold for your algorithm (again, 0.5 is perfectly reasonable) but now computing accuracy, tp, tn, fp, fn against the radiologist. 

In [27]:
algorithm_prediction = []
for i,r in labels.iterrows():
    if r['algorithm'] > 0.5:
        algorithm_prediction.append('cancer')
    else:
         algorithm_prediction.append('benign')
            

labels['algorithm_prediction'] = algorithm_prediction

algorithm_accuracy = sum(labels.radiologist == labels.algorithm_prediction)/len(labels)
algorithm_accuracy

0.87248322147651

In [28]:
confusion_matrix(labels.radiologist.values,labels.algorithm_prediction.values,labels=["cancer","benign"])

array([[ 23,  13],
       [  6, 107]])

In [34]:
algorithm_prediction = []
for i,r in labels.iterrows():
    if r['algorithm'] > 0.6:
        algorithm_prediction.append('cancer')
    else:
         algorithm_prediction.append('benign')
            

labels['algorithm_prediction'] = algorithm_prediction

algorithm_accuracy = sum(labels.radiologist == labels.algorithm_prediction)/len(labels)
algorithm_accuracy

0.87248322147651

## Reflection: 
* In the above exercise you assess performances of a human as well as of an algorithm against a 'perfect labeler' and also against each other. 
* Does accuracy seem like the appropriate statistic to use when evaluating these labels? Why or why not? 
* In what clinical settings does it seem more or less acceptable to have a high level of FNs? FPs? 
* How did changing the threshold on the algorithm performance change the different performance statistics? 
* How did your opinion of the algorithm's performance change when you started comparing it to a radiologist instead of the perfect labeler? What does this mean for a real-world scenario when a perfect labeler doesn't exist, and we only have a radiologist's read to base our performance on? 